In [5]:
import numpy as np
import cvxpy as cvx

p = cvx.Variable(4)
A = np.array([[-0.8, -0.8, 0.2, 0.2],
              [-0.6,  0.4,-0.6, 0.4],
              [ 0.0,  0.0,-0.9, 0.1]])
constraints = [0 <= p, cvx.sum_entries(p) == 1]
objective = cvx.Minimize(cvx.norm(A*p))
problem = cvx.Problem(objective, constraints)

print "Solution:", problem.solve()
print "Probabilities:"
print p.value

Solution: 0.0715859981986
Probabilities:
[[  2.38434429e-01]
 [  1.47281715e-11]
 [  1.18860860e-01]
 [  6.42704712e-01]]


In [6]:
violation_vector = A * p.value
print violation_vector

[[-0.03843443]
 [ 0.04270471]
 [-0.0427043 ]]


In [16]:
x = cvx.Variable(4)
y = cvx.Variable()

verifying = np.array([0.0, 0.0, 1.0, 1.0])
falsifying = np.array([1.0, 1.0, 0.0, 0.0])

print verifying + falsifying

lower = cvx.Minimize(verifying*x)
constraints = [x >= 0, y >= 0,
               A*x == y*violation_vector,
               cvx.sum_entries(x) == y,
               (verifying+falsifying)*x == 1]
problem_lower = cvx.Problem(lower, constraints)

upper = cvx.Maximize(verifying*x)
problem_upper = cvx.Problem(upper, constraints)

print "Lower Solution:", problem_lower.solve()
print "Lower State:", problem_lower.status
print "Upper Solution:", problem_upper.solve()
print "Upper State:", problem_upper.status

[ 1.  1.  1.  1.]
Lower Solution: 0.761565571454
Lower State: optimal
Upper Solution: 0.761565571466
Upper State: optimal
